[2023-01-08T23:27:41.655+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:26:01.217794+00:00 [queued]>
[2023-01-08T23:27:41.678+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:26:01.217794+00:00 [queued]>
[2023-01-08T23:27:41.679+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:27:41.679+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-08T23:27:41.679+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:27:41.720+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Extract_figures> on 2023-01-08 23:26:01.217794+00:00
[2023-01-08T23:27:41.733+0000] {standard_task_runner.py:55} INFO - Started process 1613 to run task
[2023-01-08T23:27:41.756+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_2020-DAG', 'Extract_figures', 'manual__2023-01-08T23:26:01.217794+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmp6hbvyog5']
[2023-01-08T23:27:41.764+0000] {standard_task_runner.py:83} INFO - Job 383: Subtask Extract_figures
[2023-01-08T23:27:42.081+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:26:01.217794+00:00 [running]> on host 3ad66d2ac9a1
[2023-01-08T23:27:42.517+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_2020-DAG
AIRFLOW_CTX_TASK_ID=Extract_figures
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T23:26:01.217794+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T23:26:01.217794+00:00
[2023-01-08T23:27:48.407+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (1,3,21) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-08T23:27:51.249+0000] {logging_mixin.py:137} INFO - Dash is running on http://localhost:7080/
[2023-01-08T23:27:51.249+0000] {dash.py:1968} INFO - Dash is running on http://localhost:7080/

[2023-01-08T23:27:51.277+0000] {logging_mixin.py:137} INFO -  * Serving Flask app 'unusual_prefix_9ec0e168250492834ce1cef2e8f4595fed38ca57_flow'
[2023-01-08T23:27:51.298+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-08T23:27:51.300+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://localhost:7080
[2023-01-08T23:27:51.301+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-08T23:29:51.458+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
